const genphy101Questions = [
    {
      name: "A book is at rest on top of a table. Which of the following is correct?",
      options: [
        "There is no force acting on the book.",
        "The book has no inertia.",
        "There is no force acting on the table.",
        "The book is in equilibrium.",
        "The inertia of the book is equal to the inertia of the table.",
      ],
      correctAnswer: "The book is in equilibrium",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "The property of a moving object to continue moving is what Galileo called",
      options: ["velocity.", "speed.", "acceleration.", "inertia.", "direction."],
      correctAnswer: "Inertia",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "According to Newton's First Law of Motion,",
      options: [
        "an object in motion eventually comes to a halt.",
        "an object at rest eventually begins to move.",
        "an object in motion moves in a parabolic trajectory unless acted upon by a net force.",
        "an object at rest always remains at rest.",
        "an object at rest remains at rest unless acted upon by a net force.",
      ],
      correctAnswer:
        "an object at rest remains at rest unless acted upon by a net force",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "If an object is moving, then the magnitude of its ____________ cannot be zero.",
      options: [
        "speed", 
        "velocity", 
        "acceleration", 
        "A and B", 
        "A, B, and C"],
      correctAnswer: "A and B",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "A car initially at rest accelerates in a straight line at 3 m/s². What will be its speed after 2 seconds?",
      options: ["0 m/s", "5 m/s", "3 m/s", "6 m/s", "2 m/s"],
      correctAnswer: "6 m/s",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "A body in free fall in a vacuum",
      options: [
        "will drop the same distance during each second of its fall.",
        "will have the same average speed during each second of its fall.",
        "will have a constant velocity during each second of its fall.",
        "will not be accelerated during its fall.",
        "will have the same acceleration during each second of its fall.",
      ],
      correctAnswer:
        "will have the same acceleration during each second of its fall",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "A bowling ball at a height of 36 meters above the ground is falling vertically at a rate of 12 meters per second. Which of these best describes its fate?",
      options: [
        "It will hit the ground in exactly three seconds at a speed of 12 m/s.",
        "It will hit the ground in less than three seconds at a speed greater than 12 m/s.",
        "It will hit the ground in more than three seconds at a speed less than 12 m/s.",
        "It will hit the ground in less than three seconds at a speed less than 12 m/s.",
        "It will hit the ground in more than three seconds at a speed greater than 12 m/s.",
      ],
      correctAnswer:
        "It will hit the ground in less than three seconds at a speed greater than 12 m/s",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "The speedometer in your car tells you the________________ of your car.",
      options: [
        "acceleration",
        "average speed",
        "instantaneous speed",
        "velocity",
        "inertia",
      ],
      correctAnswer: "instantaneous speed",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "To report the _______________ of an object, we must specify both its speed and its direction .",
      options: ["acceleration",
                "mass", 
                "velocity", 
                "length", 
                "position"],
      correctAnswer: "velocity",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "Projectile 'A' is fired at an angle of 50° above the horizontal; projectile 'B' is fired with the same speed at an angle of 40° above the horizontal. Assuming level ground and negligible air resistance, which of the following is true?",
      options: [
        "'A' will reach a greater height and have a greater range than 'B'.",
        "'A' will reach a greater height and have the same range as 'B'.",
        "'A' will reach a greater height and have a shorter range than 'B'.",
        "'A' will reach the same height and have the same range as 'B'.",
        "'A' will reach the same height and have a shorter range than 'B'.",
      ],
      correctAnswer:
        "'A' will reach the same height and have a shorter range than 'B'",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "In the absence of air resistance, the magnitude of the vertical component of a projectile's acceleration",
      options: [
        "is constant until the projectile hits the ground.",
        "always decreases with time until the projectile hits the ground.",
        "is equal to the magnitude of the horizontal component of the projectile's acceleration.",
        " increases and/or decreases with time, depending on the projectile's velocity.",
        "E. always increases with time until the projectile hits the ground.",
      ],
      correctAnswer: "is constant until the projectile hits the ground.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "A ball is thrown horizontally with a speed of 25 m/s from the top of a tower 20 meters high. Assuming level ground below and negligible air resistance, what will be the magnitude of the vertical velocity component when the ball hits the ground?",
      options: ["A. 25 m/s", "B. 15 m/s", "C. 20 m/s", "D. 50 m/s", "E. 10 m/s"],
      correctAnswer: "20 m/s",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "Which of these is the best description of the trajectory of a projectile shot from the top of a high cliff at an angle of 60° below the horizontal (neglecting air resistance)?",
      options: [
        "The projectile will move downwards at a 60° angle in a straight line at a constant speed until it stops and then falls straight down.",
        "The projectile will move downwards at a 60° angle in a straight line at a gradually diminishing speed until it stops and then falls straight down.",
        "The projectile will move downwards at a 60° angle in a straight line at a gradually increasing speed until it stops and then falls straight down.",
        "The projectile will gradually arc downward, following the curve of a circle.",
        "The projectile will gradually arc downward, following the curve of a parabola.",
      ],
      correctAnswer:
        "The projectile will gradually arc downward, following the curve of a parabola",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "A firefighter with a mass of 70 kg slides down a vertical pole, accelerating at 2 m/s². The force of friction that acts on the firefighter is",
      options: ["A. 70 N.", "B. 560 N.", "C. 140 N.", "D. 700 N.", "E. 0 N."],
      correctAnswer: "0 N",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "The of an object on the Earth's surface are directly proportional to each other.",
      options: [
        "acceleration and mass",
        "mass and weight",
        "force and velocity",
        "weight and acceleration",
        "speed and velocity",
      ],
      correctAnswer: "mass and weight",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "The Moon's gravity is 1/6 of the Earth's gravity. The weight of a bowling ball on the Earth would be its weight on the Moon.",
      options: ["equal to", "1/6 of", "6 times", "36 times", "1/36 of"],
      correctAnswer: "B. 1/6 of",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "When a certain net force is applied to one brick on a frictionless surface, it accelerates at 6 m/s². When the same net force is applied to three bricks that are cemented together,",
      options: [
        "they accelerate at 3 m/s².",
        "they accelerate at 6 m/s².",
        "they accelerate at 18 m/s².",
        "they accelerate at 2 m/s².",
        "they do not accelerate at all.",
      ],
      correctAnswer: "B. they accelerate at 6 m/s².",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "To accelerate a 6 kg mass at 2 m/s² requires a net force of .",
      options: ["A. 3 N", "B. 8 N", "C. 12 N", "D. 6 N", "E. 2 N"],
      correctAnswer: "C. 12 N",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "An element with an atomic number of 92 and an atomic mass number of 238 would have",
      options: [
        "92 protons, 146 neutrons, and 92 electrons.",
        "92 protons, 146 neutrons, and 238 electrons.",
        "92 protons, 238 neutrons, and 146 electrons.",
        "146 protons, 92 neutrons, and 92 electrons.",
        "146 protons, 92 neutrons, and 146 electrons.",
      ],
      correctAnswer: "92 protons, 146 neutrons, and 92 electrons.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "Brownian motion is the",
      options: [
        "random motion of microscopic particles being bombarded by even smaller atoms and molecules.",
        "random motion of atoms and molecules being bombarded by larger microscopic particles.",
        "vibration of atoms and molecules in a solid.",
        "movement of electrons circulating within the atom.",
        "very gradual flow of solid materials such as glass over long periods of time.",
      ],
      correctAnswer:
        "random motion of microscopic particles being bombarded by even smaller atoms and molecules.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "Chemical combinations of elements are called",
      options: ["mixtures.", "groups.", "shells.", "nuclei.", "compounds."],
      correctAnswer: "compounds.",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "Which of the following is a list of elements?",
      options: [
        "hydrogen, nitrogen, air",
        "hydrogen, oxygen, water",
        "hydrogen, oxygen, nitrogen",
        "air, nitrogen, oxygen",
        "water, nitrogen, oxygen",
      ],
      correctAnswer: "hydrogen, oxygen, nitrogen",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "Where on the periodic table would we find an element with one more proton and one more electron than silver?",
      options: [
        "Just above silver.",
        "Just to the left of silver.",
        "Just below silver.",
        "Just to the right of silver.",
        "None of these -- there is no such element.",
      ],
      correctAnswer: "Just below silver.",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "Density is",
      options: [
        "mass times volume.",
        "mass divided by volume.",
        "mass plus volume.",
        "volume divided by mass.",
        "mass minus volume.",
      ],
      correctAnswer: "mass divided by volume.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "1000 cubic centimeters of water should have a mass of approximately",
      options: [
        "100 grams",
        "10 grams",
        "1 gram",
        "1 kilogram",
        "1000 kilograms",
      ],
      correctAnswer: "1 kilogram",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "A material is said to be if it changes shape when a deforming force acts on it and returns to its original shape when the deforming force is removed.",
      options: ["elastic", "inelastic", "plastic", "stretchy", "rigid"],
      correctAnswer: "elastic",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "Hooke's Law relates the",
      options: [
        "distance a spring stretches to the force applied to the spring.",
        "distance a spring stretches to the mass of the spring.",
        "distance a spring stretches to the density of the spring.",
        "density of a spring to the force applied to the spring.",
        "density of a spring to the mass of the spring.",
      ],
      correctAnswer:
        "distance a spring stretches to the force applied to the spring.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "When the length of each edge of a cube is doubled, the cube's surface area increases by a factor of .",
      options: ["2", "4", "6", "8", "16"],
      correctAnswer: "4",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "When the length of each edge of a cube is tripled, the cube's volume",
      options: [
        "increases by a factor of 3.",
        "decreases by a factor of 1/3.",
        "increases by a factor of 9.",
        "decreases by a factor of 1/9.",
        "increases by a factor of 27.",
      ],
      correctAnswer: "increases by a factor of 27.",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "The weight of a dome produces",
      options: [
        "tension forces parallel to the curve of the dome.",
        "compression forces parallel to the curve of the dome.",
        "compression forces perpendicular to the curve of the dome.",
        "tension forces acting vertically.",
        "tension forces acting horizontally.",
      ],
      correctAnswer: "compression forces parallel to the curve of the dome.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "The buoyant force",
      options: [
        "is the force of gravity acting on a submerged object.",
        "is the difference between a submerged object's weight and the weight of an equal mass of water.",
        "is the net upward force of the surrounding liquid acting on a submerged object.",
        "is the net downward force of a submerged object acting on the surrounding liquid.",
        "depends on the density of the submerged object.",
      ],
      correctAnswer:
        "is the net upward force of the surrounding liquid acting on a submerged object.",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "The buoyant force on a block of wood floating in water",
      options: [
        "is equal to the weight of a volume of water with the same volume as the wood.",
        "is equal to the weight of the wood.",
        "is greater than the weight of the wood.",
        "is less than the weight of the wood.",
        "cannot be calculated because the block is not completely submerged.",
      ],
      correctAnswer: "is equal to the weight of the wood.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "An object with a mass of 1 kg displaces 700 ml of water. Which of the following is true?",
      options: [
        "The weight of this object is 10 N.",
        "The weight of this object is 7 N.",
        "The weight of this object is 3 N.",
        "The buoyant force on this object is 3 N.",
        "The buoyant force on this object is 10 N.",
      ],
      correctAnswer: "The buoyant force on this object is 10 N.",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "An object with a mass of 1 kg displaces 0.6 kg of water. Which of the following is true?",
      options: [
        "The buoyant force on this object is 10 N.",
        "The buoyant force on this object is 6 N.",
        "The buoyant force on this object is 4 N.",
        "The density of this object is less than that of water.",
        "This object will not sink in water.",
      ],
      correctAnswer: "The buoyant force on this object is 6 N.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "The water pressure in a lake behind a dam depends on",
      options: [
        "the volume of lake water behind the dam.",
        "the surface area of the lake.",
        "the distance from the dam at which the pressure is measured.",
        "the depth below the surface at which the pressure is measured.",
        "the number of fish in the lake.",
      ],
      correctAnswer:
        "the depth below the surface at which the pressure is measured.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "When air is removed from a metal can by a vacuum pump, the can buckles inwards and is crushed. This occurs because",
      options: [
        "the air pressure on the inside of the can is greater than the air pressure on the outside of the can.",
        "the air pressure on the outside of the can is greater than the air pressure on the inside of the can.",
        "the loss of air molecules from inside the can weakens the metal.",
        "the opposite sides of the empty can strongly attract each other.",
        "of Bernoulli's principle.",
      ],
      correctAnswer:
        "the air pressure on the outside of the can is greater than the air pressure on the inside of the can.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "Bernoulli's principle explains why",
      options: [
        "a hot air balloon rises.",
        "liquid rises in a drinking straw.",
        "airplanes fly.",
        "dead fish float.",
        "submarines can remain submerged.",
      ],
      correctAnswer: "airplanes fly.",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "In order to decrease the pressure in an automobile tire, one normally",
      options: [
        "decreases the temperature of the tire.",
        "increases the volume of the tire.",
        "increases the density of air in the tire.",
        "decreases the number of air molecules in the tire.",
        "decreases the surface area of the tire.",
      ],
      correctAnswer: "decreases the number of air molecules in the tire.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "According to Boyle's Law, if the volume occupied by a certain gas is doubled,",
      options: [
        "the pressure of the gas will be doubled.",
        "the pressure of the gas will be quadrupled.",
        "the pressure of the gas will remain constant.",
        "the pressure of the gas will be halved.",
        "the number of atoms in the gas will be halved.",
      ],
      correctAnswer: "the pressure of the gas will be halved.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "Archimedes' Principle states that an object surrounded by air is buoyed up by a force equal to the",
      options: [
        "weight of the air it displaces.",
        "weight of the object.",
        "total pressure on the object.",
        "difference between the weight of the object and the weight of the air it displaces.",
        "weight of Archimedes.",
      ],
      correctAnswer: "weight of the air it displaces.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "In general, when a liquid is heated",
      options: [
        "it will neither expand nor contract.",
        "it will expand at a greater rate than a solid.",
        "it will expand at a lesser rate than a solid.",
        "it will contract at a greater rate than a solid.",
        "it will contract at a lesser rate than a solid.",
      ],
      correctAnswer: "it will expand at a greater rate than a solid.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "If a flat metal plate with a circular hole cut through it is heated,",
      options: [
        "the hole gets smaller.",
        "the hole gets larger.",
        "the hole stays exactly the same size.",
        "the hole may get larger or smaller, depending on the material of the plate.",
        "the hole may get larger or smaller, depending on how much the plate is heated.",
      ],
      correctAnswer:
        "the hole may get larger or smaller, depending on the material of the plate.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "Water has a higher specific heat capacity than iron. This means that",
      options: [
        "water is more dense than iron.",
        "water is hotter than iron.",
        "water heats more rapidly than iron.",
        "water heats more slowly than iron.",
        "water boils at a higher temperature than iron.",
      ],
      correctAnswer: "water heats more slowly than iron.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "The specific heat capacity of water is 1 calorie per gram per degree Celsius. This means that it will take calorie(s) to increase the temperature of 10 grams of water by 10 degrees.",
      options: ["20", "0.1", "1", "10", "100"],
      correctAnswer: "100",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "Water reaches its highest density at a temperature of degrees Celsius.",
      options: ["0", "4", "10", "-10", "-4"],
      correctAnswer: "4",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "Which of these is an example of heat transfer by conduction?",
      options: [
        "The handle of a metal spoon becomes hot when you use it to stir a pot of soup on the stove.",
        "The air near the ceiling is normally warmer than air near the floor.",
        "You can boil water in a microwave oven.",
        "You feel the heat from a bonfire even though you are several meters away from it.",
        "Smoke rises up a chimney.",
      ],
      correctAnswer:
        "The handle of a metal spoon becomes hot when you use it to stir a pot of soup on the stove.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "Rising air tends to",
      options: [
        "expand and become cooler.",
        "expand and become warmer.",
        "become denser and warmer.",
        "become denser and cooler.",
        "maintain a constant density and temperature.",
      ],
      correctAnswer: "expand and become cooler.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "Radiation is heat transfer by",
      options: [
        "molecular and electronic collisions.",
        "electromagnetic waves.",
        "bulk fluid motions.",
        "atmospheric currents.",
        "direct contact.",
      ],
      correctAnswer: "electromagnetic waves.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "The pattern formed by overlapping waves in a bow wave is in the shape of the letter .",
      options: ["B", "U", "V", "I", "T"],
      correctAnswer: "V",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "The Doppler effect causes",
      options: [
        "the observed pitch of a sound to be lower if the source of sound is approaching the observer.",
        "the observed pitch of a sound to be higher if the source of sound is moving away from the observer.",
        "the observed pitch of a sound to be lower if the source of sound is moving away from the observer.",
        "the speed of sound to increase if the source of sound is moving away from the observer.",
        "the speed of sound to decrease if the source of sound is moving away from the observer.",
      ],
      correctAnswer:
        "the observed pitch of a sound to be higher if the source of sound is moving away from the observer.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "In a wave, the medium vibrates in a direction that is perpendicular to the direction the wave travels.",
      options: ["sound", "longitudinal", "perpendicular", "transverse", "normal"],
      correctAnswer: "transverse",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "The period of a pendulum depends on",
      options: [
        "the mass of the pendulum and the size of the arc it swings through.",
        "the length of the pendulum and the size of the arc it swings through.",
        "the mass of the pendulum and the acceleration of gravity.",
        "the length of the pendulum and the acceleration of gravity.",
        "the weight of the pendulum and the material it is made from.",
      ],
      correctAnswer:
        "the length of the pendulum and the acceleration of gravity.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "A wave that has a relatively long wavelength will also have a relatively",
      options: [
        "high frequency.",
        "long period.",
        "large amplitude.",
        "high speed.",
        "small amplitude.",
      ],
      correctAnswer: "small amplitude.",
      correctOption: "E",
      answerPicked: "",
    },
    {
      name: "A train of freight cars, each 10 m long, rolls by at the rate of 2 cars each second. What is the speed of the train?",
      options: ["10 m/s", "2 m/s", "5 m/s", "20 m/s", "12 m/s"],
      correctAnswer: "5 m/s",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "An object will sink in a fluid if its density is",
      options: [
        "greater than the fluid's density.",
        "less than the fluid's density.",
        "equal to the fluid's density.",
        "greater than the fluid's viscosity.",
        "less than the fluid's viscosity.",
      ],
      correctAnswer: "greater than the fluid's density.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "When a wave passes from one medium to another and changes speed, its frequency",
      options: [
        "increases.",
        "decreases.",
        "remains the same.",
        "becomes zero.",
        "doubles.",
      ],
      correctAnswer: "remains the same.",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "When light passes from air into water, it",
      options: [
        "bends toward the normal.",
        "bends away from the normal.",
        "does not bend at all.",
        "changes color.",
        "changes speed but not direction.",
      ],
      correctAnswer: "bends toward the normal.",
      correctOption: "A",
      answerPicked: "",
    },
    {
      name: "What is angular velocity in rotational dynamics?",
      options: [
        "Angular velocity measures the linear speed of an object.",
        "Angular velocity is the rate of change of angular displacement.",
        "Angular velocity is the force applied to rotate an object.",
        "Angular velocity measures the mass of a rotating object.",
      ],
      correctAnswer:
        "Angular velocity is the rate of change of angular displacement.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "What is torque in rotational dynamics?",
      options: [
        "Torque is the angular velocity of a rotating object.",
        "Torque is the same as angular displacement.",
        "Torque is the resistance to linear motion.",
        "Torque is the rotational analog of force, causing angular acceleration.",
      ],
      correctAnswer:
        "Torque is the rotational analog of force, causing angular acceleration.",
      correctOption: "D",
      answerPicked: "",
    },
    {
      name: "What is centripetal force?",
      options: [
        "Centripetal force pushes objects away from the center of rotation.",
        "Centripetal force is the force that pulls objects toward the center of circular motion.",
        "Centripetal force is the same as centrifugal force.",
        "Centripetal force only affects objects at rest.",
      ],
      correctAnswer:
        "Centripetal force is the force that pulls objects toward the center of circular motion.",
      correctOption: "B",
      answerPicked: "",
    },
    {
      name: "What is the formula for angular momentum?",
      options: [
        "Angular momentum = mass * velocity",
        "Angular momentum = force * time",
        "Angular momentum = moment of inertia * angular velocity",
        "Angular momentum = torque * distance",
      ],
      correctAnswer: "Angular momentum = moment of inertia * angular velocity",
      correctOption: "C",
      answerPicked: "",
    },
    {
      name: "What is rotational equilibrium?",
      options: [
        "Rotational equilibrium occurs when an object is not rotating at all.",
        "Rotational equilibrium occurs when the net torque on an object is zero.",
        "Rotational equilibrium occurs when an object is rotating at a constant speed.",
        "Rotational equilibrium occurs when an object is spinning uncontrollably.",
      ],
      correctAnswer:
        "Rotational equilibrium occurs when the net torque on an object is zero.",
      correctOption: "B",
      answerPicked: "",
    },
  ];
  
